name: first_workflow
on: workflow_dispatch

jobs:
  first: 
    runs-on: ubuntu-latest
    steps: 
      - name: Trigger
        run: |
              echo "Hello, world!"
              echo "Hello, world again!"
